version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "80:80"
    networks:
      - app-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
